### ISSUE TITLE
doesn't do well with Numeric columns

### ISSUE THREAD

**Issue by jakefreeberg** [marcioggs/jquery-handsontable-maxlength#1]
.val() comes back as a number and breaks the way you're checking .length on that

**Comment by marcioggs** [comment]
Hi, Jake!
Thanks for your feedback.

I've tested in Chrome 42 and it worked in this example:
http://jsfiddle.net/x0zz28fb/1/

Do you mind providing me a jsfiddle that shows the error, please?
I'm not an expert in handsontable, so you might be using some feature that breaks it.

Thanks in advance.
