### ISSUE TITLE
limit void on Paste

### ISSUE THREAD

**Issue by blacksmoke26** [marcioggs/jquery-handsontable-maxlength#4]
Plugin doesn't work after Paste (by pressing Ctrl+V).

**Comment by marcioggs** [comment]
Hello!
Do you mean pasting by Ctrl+V?
Can you reproduce in this fiddle? http://jsfiddle.net/jnsar1zy/
I've tried to, but couldn't, it pastes with no problem. And if the text is bigger than the specified, it just trims it as expected.

**Comment by blacksmoke26** [comment]
In cell editing mode, it works fine but Paste on selected cell skips chars limit.

**Comment by marcioggs** [comment]
Now I understood it! Thanks for reporting.

**Comment by marcioggs** [comment]
Fixed. :)
http://jsfiddle.net/qyptgkwk/
